### ISSUE TITLE
aishell test set decoded by streaming transformer cer cannot reach 6.6

### ISSUE THREAD

**Issue by xqq2018rebuild** [hirofumi0810/neural_sp#101]
train config:
conf/asr/transformer_mma/lc_transformer_mma_mono4H_chunk4H_chunk16_from4L_headdrop0.5_subsample8_96_64_32.yaml
Because CUDA doesn't have enough memory, I change batch_size from 32 to 16;

decode config
metric=edit_distance
batch_size=1
beam_width=10
min_len_ratio=0.0
max_len_ratio=1.0
length_penalty=2.0
length_norm=false
coverage_penalty=0.0
coverage_threshold=0.0
gnmt_decoding=false
eos_threshold=1.0
lm=
lm_second=
lm_bwd=
lm_weight=0.0
lm_second_weight=0.0
lm_bwd_weight=0.0
ctc_weight=0.0  # 1.0 for joint CTC-attention means decoding with CTC
resolving_unk=false
fwd_bwd_attention=false
bwd_attention=false
reverse_lm_rescoring=false
asr_state_carry_over=false
lm_state_carry_over=true
n_average=10  # for Transformer
oracle=false
chunk_sync=false  # for MoChA
mma_delay_threshold=8

The recognition result on the test test set is Corr:68.1% ,much lower than in README(cer:6.6)

**Comment by hirofumi0810** [comment]
@xqq2018rebuild Can you show me the detailed errors including del/ins/sub?

**Comment by xqq2018rebuild** [comment]
@hirofumi0810 Thanks for you help.
detailed errors(aishell test):
sub  9382 del 23947 ins   520 ref104765
sub  8.96 del 22.86 ins  0.50 wer 32.31
total sentence 7176, right sentence 1419, WER/SER: 32.31/80.23

**Comment by hirofumi0810** [comment]
What is the attention behaviour? Unfortunately, I cannot find the solution from that information only. I will reproduce it on the current codebase. Please wait for a few days.

**Comment by xqq2018rebuild** [comment]
Thank you. I will analyze the attention behaviour recently.

**Comment by hirofumi0810** [comment]
@xqq2018rebuild I trained the streaming MMA models with the current code and could outperforme the best results.
How was the attention plotting shown during training?

**Comment by xqq2018rebuild** [comment]
yy_aws_layer5
![下载](https://user-images.githubusercontent.com/41471880/87019454-3818dd00-c205-11ea-9df8-9b040983e19f.png)
yy_aws_layer4
![yy_4](https://user-images.githubusercontent.com/41471880/87019701-8037ff80-c205-11ea-817f-a864aec5bdc8.png)
yy_aws_layer3
![yy3](https://user-images.githubusercontent.com/41471880/87019953-d147f380-c205-11ea-9ec0-a43ca0684219.png)
yy_aws_layer2
![yy2](https://user-images.githubusercontent.com/41471880/87020004-df960f80-c205-11ea-9dbb-13aa03d084ec.png)
yy_aws_layer1
![yy1](https://user-images.githubusercontent.com/41471880/87020043-e91f7780-c205-11ea-87aa-311c1e365ec3.png)
yy_aws_layer0
![yy0](https://user-images.githubusercontent.com/41471880/87020061-f0df1c00-c205-11ea-95d2-9abcc28828cd.png)
xy_aws_beta_layer5
![xy_beta5](https://user-images.githubusercontent.com/41471880/87020083-f89ec080-c205-11ea-9d6e-f0e198bf687c.png)
xy_aws_beta_layer4
![xy_beta_4](https://user-images.githubusercontent.com/41471880/87020126-02c0bf00-c206-11ea-9b9a-97aa2f3ec96b.png)
xy_aws_beta_layer3
![xy_beta_3](https://user-images.githubusercontent.com/41471880/87020152-0bb19080-c206-11ea-88f9-588e749e77e2.png)
xy_aws_layer5
![xy5](https://user-images.githubusercontent.com/41471880/87020213-1ec46080-c206-11ea-8ec6-459874248413.png)
xy_aws_layer4
![xy4](https://user-images.githubusercontent.com/41471880/87020228-23891480-c206-11ea-9caf-86f147fd4b69.png)
xy_aws_layer3
![xy3](https://user-images.githubusercontent.com/41471880/87020240-28e65f00-c206-11ea-981f-7adc8cfa36e8.png)

**Comment by hirofumi0810** [comment]
@xqq2018rebuild hmm, training looks very good. Can you try it again with the latest codebase?

**Comment by xqq2018rebuild** [comment]
ok, I'll try again

**Comment by xqq2018rebuild** [comment]
I try again with teh latest codebase. The results as follows(No language model is used):
dev set:
sub 12950 del   265 ins   263 ref205341
sub  6.31 del  0.13 ins  0.13 wer  6.56
total sentence 14326, right sentence 7889, WER/SER: 6.56/44.93
test set:
sub 12950 del   265 ins   263 ref205341
sub  6.31 del  0.13 ins  0.13 wer  6.56
total sentence 14326, right sentence 7889, WER/SER: 6.56/44.93
