### ISSUE TITLE
How much does the LM affect the WER in the Librispeech recipe?

### ISSUE THREAD

**Issue by JiayiFu** [hirofumi0810/neural_sp#111]
Hi,
  I'm new to neural_sp and I found it's really a good project. The results showed in the Librispeech recipe readme is very good. I'm trying to reproduce the results using the recipe and I want to know how much does the LM affects the WER? For example, if I only train a model(Transformer + speed perturb + SpecAugment) without the LM, how about the performance on the test sets?
  I also found the Conformer has been implemented in this project. The result showed in Conformer's paper is better than the compared Transformer. Are there any results in neural_sp with Conformer?
  Thank you very much!

**Comment by hirofumi0810** [comment]
Hi @JiayiFu, strong LM is essential to reproduce the SOTA results on Librispeech, especially for Transformer.
If I remove LM fusion, WER drops by about 3.0 absolutely in general.

I just implemented Conformer, but there are a lot of unclear parts in the paper.
I would be grateful if you could take a look at codes (and play them a little bit) and give me some feedback.

**Comment by JiayiFu** [comment]
@hirofumi0810 Thanks for your reply!

> If I remove LM fusion, WER drops by about 3.0 absolutely in general.
Thanks for your information! Can you tell me how much time the training(AM and LM) will take if I reproduce the recipe on a server with 8 1080Tis?

> I just implemented Conformer, but there are a lot of unclear parts in the paper.
I'm trying to do some experiments based on Conformer's paper recently and also learning from your codes. If I find something interesting, I will tell you. Thanks!

**Comment by hirofumi0810** [comment]
@JiayiFu The best model takes 2 weeks with a single GPU. LM takes 3-4 weeks with a single GPU.
I don't tune configuration for multi-GPU training so much. But your contribution is welcome.

**Comment by JiayiFu** [comment]
@hirofumi0810 I get it. Thanks for your info!
