### ISSUE TITLE
 Question about the SpecAugment configuration in aishell example

### ISSUE THREAD

**Issue by iehppp2010** [hirofumi0810/neural_sp#113]
First ,thanks to your great work!

I am new to neural_sp. I have a question about the SpecAugment configuration in aishell example.
In **README.md** of aishell:

**Transformer + SpecAugment (no LM)**
conf: conf/asr/transformer.yaml
decoding parameters
n_average: 10
beam width: 5
Eval Set | # Snt | # Wrd | Corr | Sub | Del | Ins | Err | S.Err
-- | -- | -- | -- | -- | -- | -- | -- | --
dev | 14326 | 205341 | 95.1 | 4.8 | 0.1 | 0.1 | 5.0 | 36.0
test | 7176 | 104765 | 94.7 | 5.1 | 0.2 | 0.1 | 5.4 | 37.7

'''

I don't find '**n_freq_masks**' or '**n_time_masks**' config in the config yaml.

Since their default value was 0, SpecAugment will not work.

So, just setting 'n_freq_masks=1' and 'n_time_masks=1' , will that be correct?

**Comment by hirofumi0810** [comment]
@iehppp2010 You need to set `--conf2` to `conf/data/spec_augment_speed_perturb_transformer.yaml`.
I will update README.md for clarity.

**Comment by iehppp2010** [comment]
@hirofumi0810 Thanks for your answer, I'll close this.
