### ISSUE TITLE
How many gpus do you use for aishell dataset?

### ISSUE THREAD

**Issue by cywang97** [hirofumi0810/neural_sp#115]
Hi,  I realize the `accum_grad_n_step` argument is set to 8 in transformer.yaml, I want to know that how many gpus do you use when you train models for this setting.  Should I change it to 2 when I use 4 gpus to reproduce your results?

**Comment by hirofumi0810** [comment]
Hi @cywang97, I usually use a single GPU on AISHELL-1:)
In general, a good rule of thumb is to reduce accumulation when using multiple GPUs to keep total mini-batch size at a single parameter update step.
Maybe accum8 + 4GPUs leads to too slow convergence.
