### ISSUE TITLE
bug: bugs when use multi-gpu training

### ISSUE THREAD

**Issue by cywang97** [hirofumi0810/neural_sp#116]
Hi, hiro, I use multi GPU to train an ASR model.  It seems torch.nn.parallel.DataParallel won't scatter the dict input. You should overwrite the scatter function in CustomDataParallel function to make sure each item in the dict can be scattered on different devices.

**Comment by hirofumi0810** [comment]
@cywang97 Thank you for your report. As I usually use a single GPU, I didn't notice that. I will check and fix it.

**Comment by kangj13** [comment]
Hi, I met similar problem using multi GPUs. 
![image](https://user-images.githubusercontent.com/5909894/91987820-1baaa400-ed61-11ea-97b1-be9c20815377.png)
It seems all parameters are only on GPU 0 and inputs on GPU 1.
