### ISSUE TITLE
Makefile error

### ISSUE THREAD

**Issue by dengxiaotian123** [hirofumi0810/neural_sp#181]
When installing warp-ctc with GPU, the variable CUPY_VERSION should be CUDA_VERSION. Otherwise, the CPU version will be installed. Then, run satge=4 ,there will be a message: AttributeError: module 'warpctc_pytorch' has no attribute 'gpu_ctc'

**Comment by hirofumi0810** [comment]
@dengxiaotian123 Did you set path to CUDA, NCCL before installation?

**Comment by hirofumi0810** [comment]
Fixed by #232.
