### ISSUE TITLE
relative positional encoding

### ISSUE THREAD

**Issue by zyzpower** [hirofumi0810/neural_sp#184]
Hi, which dataset/configuration is relative positional encoding implemented? Is the transformer-XL implemented in encoder?

**Comment by hirofumi0810** [comment]
@zyzpower Yes. `relative` and `relative_xl` options correspond to relative positional encoding.
But I didn't implement recurrence like Transformer-XL because it breaks the parallel computation.
Transformer-XL LM is already implemented.
