### ISSUE TITLE
Librispeech results

### ISSUE THREAD

**Issue by stefan-falk** [hirofumi0810/neural_sp#186]
I just have a question regarding these results:

![image](https://user-images.githubusercontent.com/43335432/98555710-8e288a80-22a2-11eb-8b72-8f315b0d8285.png)

What training data has been used there? Was it the entire `train` set or only the `clean` audios were these results evaluated by simulating audio-streaming?

**Comment by hirofumi0810** [comment]
Training data is the standard 960-hour set.

**Comment by stefan-falk** [comment]
Thank you :)
