### ISSUE TITLE
module 'warpctc_pytorch' has no attribute 'gpu_ctc'

### ISSUE THREAD

**Issue by zyzpower** [hirofumi0810/neural_sp#190]
Hi, I am trying to reproduce the transformer result on Librispeech, however at stage 4, I encounter an error of "module 'warpctc_pytorch' has no attribute 'gpu_ctc' " when calculating the ctc loss. Any idea why?

**Comment by hirofumi0810** [comment]
@zyzpower Did you set path to CUDA, NCCL before installation?

**Comment by zyzpower** [comment]
hi, you mean this setting right
CUDAROOT=/usr/local/cuda
NCCL_ROOT=/usr/local/nccl

**Comment by hirofumi0810** [comment]
@zyzpower I think you failed to compile `warp-ctc` on the GPU mode. Instead, you can also use the native CTC on pytorch.

**Comment by hirofumi0810** [comment]
Same issue as #181. Already fixed by #232.
