### ISSUE TITLE
Sorry, I can not find the 'AcousticModel' code ?

### ISSUE THREAD

**Issue by Gqwert123** [hirofumi0810/neural_sp#24]
I can not find the code difine, can any one help?
neural_sp/neural_sp/bin/asr/train.py /
from neural_sp.models.seq2seq.acoustic_model import AcousticModel

**Comment by zhazhuanling** [comment]
Same to me, can you provided it?@hirofumi0810

**Comment by hirofumi0810** [comment]
Fixed in #26.
