### ISSUE TITLE
a question about transducer training

### ISSUE THREAD

**Issue by jinggaizi** [hirofumi0810/neural_sp#292]
@hirofumi0810 
hi, author, i train a model with transducer configuration, it's failed while processing batch_dev, the code is as follow:
batch_dev = iter(dev_set).next(batch_size=1 if 'transducer' in args.dec_type else None)[0]----neural_sp/bin/asr/train.py
the batch_dev has only one item but it's need data parallel when run "loss, observation = model(batch_dev, task=task, is_eval=True)", the result of "res = [{k: scatter_map(v, i) for k, v in inputs.items()} for i in range(len(self.device_ids))]"----torch/nn/parallel/data_parallel.py is null,
Is there a problem with the code or data? i run the case in aishell

**Comment by hirofumi0810** [comment]
#307 fixed it.
