### ISSUE TITLE
librispeech dict issue vocab

### ISSUE THREAD

**Issue by qkrguswn2401** [hirofumi0810/neural_sp#348]
I an running librispeech example.  under dict folder, there are bpe10000.vocab and wpbpe100000.txt.  
Vocab file is the vocab file
The wpbpe10000.txt contains only <unk>, <eos>, <pad>.
When running language model, the dict.txt of the model is the wpbpe10000.txt (3 vocabs), which does not make sense!  
Did I make the wpbpe10000.txt wrong?

**Comment by qkrguswn2401** [comment]
![image](https://user-images.githubusercontent.com/36841216/161706770-38839cee-88e5-4ba9-bb27-33370c1d933a.png)

**Comment by qkrguswn2401** [comment]
![image](https://user-images.githubusercontent.com/36841216/161706806-f9ea25a2-f4da-44c4-8210-57f4c61a171b.png)
this is the dict.txt that Language model uses

**Comment by MM-0712** [comment]
Yes, the dict seems error. It need to check carefully again. 

Best
Guodong
