### ISSUE TITLE
A problem about shallow fusion

### ISSUE THREAD

**Issue by Marcovaldong** [hirofumi0810/neural_sp#5]
Hi , thanks for your uploading code. have you uploaded the code os shallow fusion, I didn't find it.

**Comment by hirofumi0810** [comment]
@Marcovaldong Please check examples/corpus/**/local/score.sh.
You can evaluate the model with score.sh after finishing training (stage-4).

**Comment by Marcovaldong** [comment]
Tks, I will try your code.
