### ISSUE TITLE
why mask=None in stream mode

### ISSUE THREAD

**Issue by Cescfangs** [hirofumi0810/neural_sp#53]
https://github.com/hirofumi0810/neural_sp/blob/cf73c78148d5e5095f03324fb47e9be9bbd47e32/neural_sp/models/seq2seq/encoders/transformer.py#L373

**Comment by hirofumi0810** [comment]
@Cescfangs This is because all timesteps in a chunk might be masked for some utterances in a mini-batch.

**Comment by Cescfangs** [comment]
Thanks
