### ISSUE TITLE
How much GPU memory do we need to run librispeech lstm_mocha.yaml?

### ISSUE THREAD

**Issue by Park-Jong-Min** [hirofumi0810/neural_sp#59]
I try to run lstm_mocha.conf script in librispeech example.
But, out of memory occurs in a 24GB size GPU when I try to run the scripted with reference batch_size (30).
How much GPU memory is need for librispeech lstm_mocha.yaml?
Or, Can I get similar WER rate with accum_grad_n_steps option with lower batch_size in lstm_mocha.yaml?

**Comment by hirofumi0810** [comment]
@Park-Jong-Min I could run the script on a single GPU with 12GB. Can you try to reduce the batch size? I'm not sure how gradient accumulation affects the performance of RNN models.

**Comment by Park-Jong-Min** [comment]
> @Park-Jong-Min I could run the script on a single GPU with 12GB. Can you try to reduce the batch size? I'm not sure how gradient accumulation affects the performance of RNN models.

Thank you for  your quick response!
I try to run mocha script with single GPU with batch size 30. It works well!

Have you also conducted a test of batch size 30 with multiple GPUs?

**Comment by hirofumi0810** [comment]
No, I always use a single GPU for RNN models.

**Comment by Park-Jong-Min** [comment]
Thank you!!!
