### ISSUE TITLE
How can I reproduce mocha WER in Librispeech?

### ISSUE THREAD

**Issue by Park-Jong-Min** [hirofumi0810/neural_sp#67]
I want to reproduce Librispeech MOCHA WER in this paper (CTC-synchronous Training for Monotonic Attention Model).
When I use conf file "lstm_mocha.yaml" in librispeech example, it was reduced from 700% wer at first to 100% wer at 35 epoch without lm.
I just change conf in run.sh and training with 1 GPU.
I would like to know if there is anything else that needs to be modified to make the wer in addition to the conf on run.sh.

**Comment by hirofumi0810** [comment]
How was the learning curve? I think you have the transition of WER during training.

**Comment by Park-Jong-Min** [comment]
My learning curve is looks weird.
![image](https://user-images.githubusercontent.com/33490998/84623451-3ddb1580-af1a-11ea-8f88-e60611cafd17.png)

**Comment by hirofumi0810** [comment]
How was the accuracy

**Comment by Park-Jong-Min** [comment]
This is my acc plot.
![image](https://user-images.githubusercontent.com/33490998/84623728-d8d3ef80-af1a-11ea-96e7-07776672d4ab.png)

**Comment by hirofumi0810** [comment]
I will show you the plotting of the model used in the paper.
![loss](https://user-images.githubusercontent.com/17924227/84623954-60216300-af1b-11ea-8ddb-c8591449d1d4.png)
![acc](https://user-images.githubusercontent.com/17924227/84623955-61eb2680-af1b-11ea-98b3-ea0189dcdc4f.png)
![edit_distance](https://user-images.githubusercontent.com/17924227/84623960-63b4ea00-af1b-11ea-8741-b415bb6dac6a.png)

**Comment by Park-Jong-Min** [comment]
thank you, i'll try to replot it.

**Comment by Park-Jong-Min** [comment]
I try to replot it. loss and acc look similar but still WER is too high.
I use beam search width 1 which means greedy decoding.

My decoding result looks like _**as prose to me and a later streets of stern with throngs of well rescue families in way either in the world's and a little and a little and a little and a little and a little and a little and a little and a little and a little and a little and a little and a little and a little and a little and a little and a little and a little and a little and a little and a little and a little and a little and a little and a little and a little and a little .....**_.

If i use beamsearch width 10 and length penalty 2.0, It takes about seven hours to run only one epoch.
Is there a good way to solve a problem like the above sentence other than using beamssearch and length penalty in mocha?
I wonder how long it takes to converge lstm_mocha without LM .

**Comment by hirofumi0810** [comment]
I have never experienced such behaviors.
One simple debugging is to train the model with a bidirectional encoder.
The optimization should be easier.

**Comment by Park-Jong-Min** [comment]
![image](https://user-images.githubusercontent.com/33490998/86080846-cb983280-bace-11ea-9d58-57058deba710.png)
 After I fix quantity loss to 0.05 it shows similar edit distance!

**Comment by hirofumi0810** [comment]
@Park-Jong-Min Great. Did you use 0.01 before? Actually, this number is tuned with BLSTM/LS-BLSTM encoders.
I will try 0.2 with the unidirectional encoder. Thank you for your report!

**Comment by Park-Jong-Min** [comment]
Yes, I use 0.01 before.
