### ISSUE TITLE
Errors when running make KALDI-/path/to/kaldi command

### ISSUE THREAD

**Issue by rdoshi96** [hirofumi0810/neural_sp#7]
I get the following make error related to Bazel:

command -v bazel > /dev/null || echo "SentencePiece requires Bazel, see https://bazel.build/"
cd /home/rohan_doshi96/neural_sp/tools/sentencepiece && bazel build src:all --incompatible_disable_deprecated_attr_
params=false
Extracting Bazel installation...
ERROR: The 'build' command is only supported from within a workspace (below a directory having a WORKSPACE file).
See documentation at https://docs.bazel.build/versions/master/build-ref.html#workspace
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel
 shutdown".
Makefile:92: recipe for target 'sentencepiece.done' failed
make: *** [sentencepiece.done] Error 2

**Comment by ahmedbhna** [comment]
Install SentencePiece manuelly just clone it from GitHub repo and build it.
