### ISSUE TITLE
python: can't open file 'check_install.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by WanderingSven** [hirofumi0810/neural_sp#76]
hello,everyone. When I install neural_sp, the error that "python: can't open file 'check_install.py': [Errno 2] No such file or directory"
occur. At the same time, I cannot find check_install.py. what should I do to solve this problem.

![图片](https://user-images.githubusercontent.com/26950286/85841057-1d3f7500-b7d0-11ea-8086-d345dea99986.png)

**Comment by sean186** [comment]
hello, I have the same problem. Have you solved it ? thank you

**Comment by hirofumi0810** [comment]
@WanderingSven @sean186 This was fixed in #114.
